# 0. Load imports

In [3]:
## imports
import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt
import seaborn as sns

## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv("https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv")

In [4]:
df

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
0,402374.0,132186.0,10251445,2020/09/11 04:00:00+00,2010/09/02 04:00:00+00,2010/09/02 04:00:00+00,2300 - 2399 BLOCK OF AINGER PLACE SE,HOMICIDE,GUN,MIDNIGHT,...,007502 1,7502.0,Precinct 134,NaN,402374.0,132186.0,38.857483,-76.972648,921212443,NaN
1,397920.0,136943.0,5370,2020/01/17 02:39:05+00,2020/01/11 02:48:51+00,2020/01/17 02:48:54+00,800 - 899 BLOCK OF 9TH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,005802 5,5802.0,Precinct 129,DOWNTOWN,397920.0,136943.0,38.900337,-77.023979,921212447,NaN
2,402411.0,131808.0,10147537,2020/12/21 05:00:00+00,2010/10/10 02:00:00+00,NaN,2300 - 2499 BLOCK OF HARTFORD STREET SE,HOMICIDE,OTHERS,MIDNIGHT,...,007408 2,7408.0,Precinct 115,NaN,402411.0,131808.0,38.854078,-76.972223,921212449,NaN
3,398389.0,140433.0,20000957,2020/01/02 18:53:05+00,2019/12/30 20:00:20+00,2020/01/02 18:53:32+00,3300 - 3399 BLOCK OF PARK PLACE NW,THEFT/OTHER,OTHERS,DAY,...,003200 3,3200.0,Precinct 38,NaN,398389.0,140433.0,38.931777,-77.018580,921213797,NaN
4,398946.0,139092.0,20001080,2020/01/03 01:55:16+00,2020/01/02 20:39:16+00,2020/01/02 22:20:27+00,2200 - 2299 BLOCK OF 1ST STREET NW,BURGLARY,OTHERS,EVENING,...,003301 1,3301.0,Precinct 135,NaN,398946.0,139092.0,38.919698,-77.012154,921213798,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,397241.0,140302.0,20097822,2020/07/06 22:02:48+00,2020/07/06 20:42:59+00,2020/07/06 21:00:41+00,1325 - 1399 BLOCK OF PARK ROAD NW,ASSAULT W/DANGEROUS WEAPON,KNIFE,EVENING,...,002900 2,2900.0,Precinct 41,NaN,397241.0,140302.0,38.930594,-77.031820,921779024,NaN
27928,397328.0,139157.0,20100870,2020/07/13 22:12:52+00,2020/07/07 18:00:45+00,2020/07/07 20:00:57+00,1300 - 1399 BLOCK OF FLORIDA AVENUE NW,THEFT F/AUTO,OTHERS,EVENING,...,004401 2,4401.0,Precinct 22,NaN,397328.0,139157.0,38.920280,-77.030812,921779025,NaN
27929,405049.0,136086.0,20101193,2020/07/14 14:32:30+00,2020/07/11 22:00:31+00,2020/07/14 14:28:59+00,4200 - 4243 BLOCK OF BENNING ROAD NE,THEFT/OTHER,OTHERS,DAY,...,007803 4,7803.0,Precinct 99,NaN,405049.0,136086.0,38.892605,-76.941800,921779026,NaN
27930,399823.0,138853.0,20400676,2020/05/01 18:58:30+00,2020/05/01 15:00:00+00,2020/05/01 15:35:00+00,1948 - 2099 BLOCK OF 3RD STREET NE,THEFT F/AUTO,OTHERS,DAY,...,008702 1,8702.0,Precinct 75,NaN,399823.0,138853.0,38.917546,-77.002041,921779089,NaN
27931,400801.0,129945.0,20141517,2020/10/04 03:24:25+00,2020/10/04 01:03:42+00,2020/10/04 02:58:27+00,900 - 1299 BLOCK OF VALLEY AVENUE SE,MOTOR VEHICLE THEFT,OTHERS,MIDNIGHT,...,009700 3,9700.0,Precinct 121,NaN,400801.0,129945.0,38.837298,-76.990774,921779151,NaN

# 1. Questions: list comprehension

- In class example, why did we need the "courses" at the beginning of the list iteration
- How did the join syntax work in the example where we paste together offenses from same ward

In [5]:
## toy example

### pool of courses
all_courses = ["QSS20", "QSS17", "GOV10", "GOV4", "CSC1"]

## 1.1 Application 1: filtering to a smaller list

When we might use: have a lot of columns in a dataframe; want to filter to a smaller set using some pattern

In [6]:
### pull out ones that contain GOV in the string
gov_c = [course for course in all_courses if "GOV" in course]
gov_c # result

['GOV10', 'GOV4']

In [7]:
### showing that the "course" is just a placeholder/
### arbitrary interator
gov_c_alt = [x for x in all_courses if "GOV" in x]

gov_c == gov_c_alt

True

## 1.2 Application two: keep all objects in the list but do some transformation

In [8]:
all_courses

## strip the numbers from the course names
courses_prefix = [x[:3] for x in all_courses]
courses_prefix # could then find unique elements

['QSS20', 'QSS17', 'GOV10', 'GOV4', 'CSC1']

['QSS', 'QSS', 'GOV', 'GOV', 'CSC']

In [9]:
# Join all together example
" #:(# ".join(courses_prefix)

'QSS #:(# QSS #:(# GOV #:(# GOV #:(# CSC'

#### Your turn: Using original list, add "dartmouth_" prefix to the course name

In [23]:
prefix = "dartmouth_"
dartmouth_prefix = [prefix + course for course in all_courses ]
dartmouth_prefix

['dartmouth_QSS20',
 'dartmouth_QSS17',
 'dartmouth_GOV10',
 'dartmouth_GOV4',
 'dartmouth_CSC1']

## 1.3 Subsetting columns

Use list comprehension to filter to columns with id in the string. Then, create a new dataframe called df1 that contains only column heads with "id"

In [25]:
id_cols = [col for col in df.columns if "ID" in col]
id_cols

## Then, filter the data
df[id_cols]

['BID', 'OBJECTID', 'OCTO_RECORD_ID']

            BID   OBJECTID  OCTO_RECORD_ID
0           NaN  921212443             NaN
1      DOWNTOWN  921212447             NaN
2           NaN  921212449             NaN
3           NaN  921213797             NaN
4           NaN  921213798             NaN
...         ...        ...             ...
27927       NaN  921779024             NaN
27928       NaN  921779025             NaN
27929       NaN  921779026             NaN
27930       NaN  921779089             NaN
27931       NaN  921779151             NaN

[27932 rows x 3 columns]

## 1.4 Comprehension for numbers

Here we compare two ways of creating a list of even numbers.

In [26]:
num_list = np.arange(10000)
num_list

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [27]:
%%time
even_nums = [i for i in num_list if (i % 2) == 0]
even_nums

CPU times: user 1.49 ms, sys: 184 μs, total: 1.67 ms
Wall time: 1.72 ms

[np.int64(0),
 np.int64(2),
 np.int64(4),
 np.int64(6),
 np.int64(8),
 np.int64(10),
 np.int64(12),
 np.int64(14),
 np.int64(16),
 np.int64(18),
 np.int64(20),
 np.int64(22),
 np.int64(24),
 np.int64(26),
 np.int64(28),
 np.int64(30),
 np.int64(32),
 np.int64(34),
 np.int64(36),
 np.int64(38),
 np.int64(40),
 np.int64(42),
 np.int64(44),
 np.int64(46),
 np.int64(48),
 np.int64(50),
 np.int64(52),
 np.int64(54),
 np.int64(56),
 np.int64(58),
 np.int64(60),
 np.int64(62),
 np.int64(64),
 np.int64(66),
 np.int64(68),
 np.int64(70),
 np.int64(72),
 np.int64(74),
 np.int64(76),
 np.int64(78),
 np.int64(80),
 np.int64(82),
 np.int64(84),
 np.int64(86),
 np.int64(88),
 np.int64(90),
 np.int64(92),
 np.int64(94),
 np.int64(96),
 np.int64(98),
 np.int64(100),
 np.int64(102),
 np.int64(104),
 np.int64(106),
 np.int64(108),
 np.int64(110),
 np.int64(112),
 np.int64(114),
 np.int64(116),
 np.int64(118),
 np.int64(120),
 np.int64(122),
 np.int64(124),
 np.int64(126),
 np.int64(128),
 np.int64(130),
 np.int64(132),
 np.int64(134),
 np.int64(136),
 np.int64(138),
 np.int64(140),
 np.int64(142),
 np.int64(144),
 np.int64(146),
 np.int64(148),
 np.int64(150),
 np.int64(152),
 np.int64(154),
 np.int64(156),
 np.int64(158),
 np.int64(160),
 np.int64(162),
 np.int64(164),
 np.int64(166),
 np.int64(168),
 np.int64(170),
 np.int64(172),
 np.int64(174),
 np.int64(176),
 np.int64(178),
 np.int64(180),
 np.int64(182),
 np.int64(184),
 np.int64(186),
 np.int64(188),
 np.int64(190),
 np.int64(192),
 np.int64(194),
 np.int64(196),
 np.int64(198),
 np.int64(200),
 np.int64(202),
 np.int64(204),
 np.int64(206),
 np.int64(208),
 np.int64(210),
 np.int64(212),
 np.int64(214),
 np.int64(216),
 np.int64(218),
 np.int64(220),
 np.int64(222),
 np.int64(224),
 np.int64(226),
 np.int64(228),
 np.int64(230),
 np.int64(232),
 np.int64(234),
 np.int64(236),
 np.int64(238),
 np.int64(240),
 np.int64(242),
 np.int64(244),
 np.int64(246),
 np.int64(248),
 np.int64(250),
 np.int64(252),
 np.int64(254),
 np.int64(256),
 np.int64(258),
 np.int64(260),
 np.int64(262),
 np.int64(264),
 np.int64(266),
 np.int64(268),
 np.int64(270),
 np.int64(272),
 np.int64(274),
 np.int64(276),
 np.int64(278),
 np.int64(280),
 np.int64(282),
 np.int64(284),
 np.int64(286),
 np.int64(288),
 np.int64(290),
 np.int64(292),
 np.int64(294),
 np.int64(296),
 np.int64(298),
 np.int64(300),
 np.int64(302),
 np.int64(304),
 np.int64(306),
 np.int64(308),
 np.int64(310),
 np.int64(312),
 np.int64(314),
 np.int64(316),
 np.int64(318),
 np.int64(320),
 np.int64(322),
 np.int64(324),
 np.int64(326),
 np.int64(328),
 np.int64(330),
 np.int64(332),
 np.int64(334),
 np.int64(336),
 np.int64(338),
 np.int64(340),
 np.int64(342),
 np.int64(344),
 np.int64(346),
 np.int64(348),
 np.int64(350),
 np.int64(352),
 np.int64(354),
 np.int64(356),
 np.int64(358),
 np.int64(360),
 np.int64(362),
 np.int64(364),
 np.int64(366),
 np.int64(368),
 np.int64(370),
 np.int64(372),
 np.int64(374),
 np.int64(376),
 np.int64(378),
 np.int64(380),
 np.int64(382),
 np.int64(384),
 np.int64(386),
 np.int64(388),
 np.int64(390),
 np.int64(392),
 np.int64(394),
 np.int64(396),
 np.int64(398),
 np.int64(400),
 np.int64(402),
 np.int64(404),
 np.int64(406),
 np.int64(408),
 np.int64(410),
 np.int64(412),
 np.int64(414),
 np.int64(416),
 np.int64(418),
 np.int64(420),
 np.int64(422),
 np.int64(424),
 np.int64(426),
 np.int64(428),
 np.int64(430),
 np.int64(432),
 np.int64(434),
 np.int64(436),
 np.int64(438),
 np.int64(440),
 np.int64(442),
 np.int64(444),
 np.int64(446),
 np.int64(448),
 np.int64(450),
 np.int64(452),
 np.int64(454),
 np.int64(456),
 np.int64(458),
 np.int64(460),
 np.int64(462),
 np.int64(464),
 np.int64(466),
 np.int64(468),
 np.int64(470),
 np.int64(472),
 np.int64(474),
 np.int64(476),
 np.int64(478),
 np.int64(480),
 np.int64(482),
 np.int64(484),
 np.int64(486),
 np.int64(488),
 np.int64(490),
 np.int64(492),
 np.int64(494),
 np.int64(496),
 np.int64(498),
 np.int64(500),
 np.int64(502),
 np.int64(504),
 np.int64(506),
 np.int64(508),
 np.int64(510),
 np.int64(512),
 np.int64(514),
 np.int64(516),
 np.int64(518),
 np.int64(520),
 np.int64(522),
 np.int64(524),
 np.int64(526),
 np.int64(528),
 np.int64(530),
 np.int64(532),
 np.int64(534),
 np.int64(536),
 np.int64(538),
 np.int64(540),
 np.int64(542),
 np.int64(544),
 np.int64(546),
 np.int64(548),
 np.int64(550),
 np.int64(552),
 np.int64(554),
 np.int64(556),
 np.int64(558),
 np.int64(560),
 np.int64(562),
 np.int64(564),
 np.int64(566),
 np.int64(568),
 np.int64(570),
 np.int64(572),
 np.int64(574),
 np.int64(576),
 np.int64(578),
 np.int64(580),
 np.int64(582),
 np.int64(584),
 np.int64(586),
 np.int64(588),
 np.int64(590),
 np.int64(592),
 np.int64(594),
 np.int64(596),
 np.int64(598),
 np.int64(600),
 np.int64(602),
 np.int64(604),
 np.int64(606),
 np.int64(608),
 np.int64(610),
 np.int64(612),
 np.int64(614),
 np.int64(616),
 np.int64(618),
 np.int64(620),
 np.int64(622),
 np.int64(624),
 np.int64(626),
 np.int64(628),
 np.int64(630),
 np.int64(632),
 np.int64(634),
 np.int64(636),
 np.int64(638),
 np.int64(640),
 np.int64(642),
 np.int64(644),
 np.int64(646),
 np.int64(648),
 np.int64(650),
 np.int64(652),
 np.int64(654),
 np.int64(656),
 np.int64(658),
 np.int64(660),
 np.int64(662),
 np.int64(664),
 np.int64(666),
 np.int64(668),
 np.int64(670),
 np.int64(672),
 np.int64(674),
 np.int64(676),
 np.int64(678),
 np.int64(680),
 np.int64(682),
 np.int64(684),
 np.int64(686),
 np.int64(688),
 np.int64(690),
 np.int64(692),
 np.int64(694),
 np.int64(696),
 np.int64(698),
 np.int64(700),
 np.int64(702),
 np.int64(704),
 np.int64(706),
 np.int64(708),
 np.int64(710),
 np.int64(712),
 np.int64(714),
 np.int64(716),
 np.int64(718),
 np.int64(720),
 np.int64(722),
 np.int64(724),
 np.int64(726),
 np.int64(728),
 np.int64(730),
 np.int64(732),
 np.int64(734),
 np.int64(736),
 np.int64(738),
 np.int64(740),
 np.int64(742),
 np.int64(744),
 np.int64(746),
 np.int64(748),
 np.int64(750),
 np.int64(752),
 np.int64(754),
 np.int64(756),
 np.int64(758),
 np.int64(760),
 np.int64(762),
 np.int64(764),
 np.int64(766),
 np.int64(768),
 np.int64(770),
 np.int64(772),
 np.int64(774),
 np.int64(776),
 np.int64(778),
 np.int64(780),
 np.int64(782),
 np.int64(784),
 np.int64(786),
 np.int64(788),
 np.int64(790),
 np.int64(792),
 np.int64(794),
 np.int64(796),
 np.int64(798),
 np.int64(800),
 np.int64(802),
 np.int64(804),
 np.int64(806),
 np.int64(808),
 np.int64(810),
 np.int64(812),
 np.int64(814),
 np.int64(816),
 np.int64(818),
 np.int64(820),
 np.int64(822),
 np.int64(824),
 np.int64(826),
 np.int64(828),
 np.int64(830),
 np.int64(832),
 np.int64(834),
 np.int64(836),
 np.int64(838),
 np.int64(840),
 np.int64(842),
 np.int64(844),
 np.int64(846),
 np.int64(848),
 np.int64(850),
 np.int64(852),
 np.int64(854),
 np.int64(856),
 np.int64(858),
 np.int64(860),
 np.int64(862),
 np.int64(864),
 np.int64(866),
 np.int64(868),
 np.int64(870),
 np.int64(872),
 np.int64(874),
 np.int64(876),
 np.int64(878),
 np.int64(880),
 np.int64(882),
 np.int64(884),
 np.int64(886),
 np.int64(888),
 np.int64(890),
 np.int64(892),
 np.int64(894),
 np.int64(896),
 np.int64(898),
 np.int64(900),
 np.int64(902),
 np.int64(904),
 np.int64(906),
 np.int64(908),
 np.int64(910),
 np.int64(912),
 np.int64(914),
 np.int64(916),
 np.int64(918),
 np.int64(920),
 np.int64(922),
 np.int64(924),
 np.int64(926),
 np.int64(928),
 np.int64(930),
 np.int64(932),
 np.int64(934),
 np.int64(936),
 np.int64(938),
 np.int64(940),
 np.int64(942),
 np.int64(944),
 np.int64(946),
 np.int64(948),
 np.int64(950),
 np.int64(952),
 np.int64(954),
 np.int64(956),
 np.int64(958),
 np.int64(960),
 np.int64(962),
 np.int64(964),
 np.int64(966),
 np.int64(968),
 np.int64(970),
 np.int64(972),
 np.int64(974),
 np.int64(976),
 np.int64(978),
 np.int64(980),
 np.int64(982),
 np.int64(984),
 np.int64(986),
 np.int64(988),
 np.int64(990),
 np.int64(992),
 np.int64(994),
 np.int64(996),
 np.int64(998),
 np.int64(1000),
 np.int64(1002),
 np.int64(1004),
 np.int64(1006),
 np.int64(1008),
 np.int64(1010),
 np.int64(1012),
 np.int64(1014),
 np.int64(1016),
 np.int64(1018),
 np.int64(1020),
 np.int64(1022),
 np.int64(1024),
 np.int64(1026),
 np.int64(1028),
 np.int64(1030),
 np.int64(1032),
 np.int64(1034),
 np.int64(1036),
 np.int64(1038),
 np.int64(1040),
 np.int64(1042),
 np.int64(1044),
 np.int64(1046),
 np.int64(1048),
 np.int64(1050),
 np.int64(1052),
 np.int64(1054),
 np.int64(1056),
 np.int64(1058),
 np.int64(1060),
 np.int64(1062),
 np.int64(1064),
 np.int64(1066),
 np.int64(1068),
 np.int64(1070),
 np.int64(1072),
 np.int64(1074),
 np.int64(1076),
 np.int64(1078),
 np.int64(1080),
 np.int64(1082),
 np.int64(1084),
 np.int64(1086),
 np.int64(1088),
 np.int64(1090),
 np.int64(1092),
 np.int64(1094),
 np.int64(1096),
 np.int64(1098),
 np.int64(1100),
 np.int64(1102),
 np.int64(1104),
 np.int64(1106),
 np.int64(1108),
 np.int64(1110),
 np.int64(1112),
 np.int64(1114),
 np.int64(1116),
 np.int64(1118),
 np.int64(1120),
 np.int64(1122),
 np.int64(1124),
 np.int64(1126),
 np.int64(1128),
 np.int64(1130),
 np.int64(1132),
 np.int64(1134),
 np.int64(1136),
 np.int64(1138),
 np.int64(1140),
 np.int64(1142),
 np.int64(1144),
 np.int64(1146),
 np.int64(1148),
 np.int64(1150),
 np.int64(1152),
 np.int64(1154),
 np.int64(1156),
 np.int64(1158),
 np.int64(1160),
 np.int64(1162),
 np.int64(1164),
 np.int64(1166),
 np.int64(1168),
 np.int64(1170),
 np.int64(1172),
 np.int64(1174),
 np.int64(1176),
 np.int64(1178),
 np.int64(1180),
 np.int64(1182),
 np.int64(1184),
 np.int64(1186),
 np.int64(1188),
 np.int64(1190),
 np.int64(1192),
 np.int64(1194),
 np.int64(1196),
 np.int64(1198),
 np.int64(1200),
 np.int64(1202),
 np.int64(1204),
 np.int64(1206),
 np.int64(1208),
 np.int64(1210),
 np.int64(1212),
 np.int64(1214),
 np.int64(1216),
 np.int64(1218),
 np.int64(1220),
 np.int64(1222),
 np.int64(1224),
 np.int64(1226),
 np.int64(1228),
 np.int64(1230),
 np.int64(1232),
 np.int64(1234),
 np.int64(1236),
 np.int64(1238),
 np.int64(1240),
 np.int64(1242),
 np.int64(1244),
 np.int64(1246),
 np.int64(1248),
 np.int64(1250),
 np.int64(1252),
 np.int64(1254),
 np.int64(1256),
 np.int64(1258),
 np.int64(1260),
 np.int64(1262),
 np.int64(1264),
 np.int64(1266),
 np.int64(1268),
 np.int64(1270),
 np.int64(1272),
 np.int64(1274),
 np.int64(1276),
 np.int64(1278),
 np.int64(1280),
 np.int64(1282),
 np.int64(1284),
 np.int64(1286),
 np.int64(1288),
 np.int64(1290),
 np.int64(1292),
 np.int64(1294),
 np.int64(1296),
 np.int64(1298),
 np.int64(1300),
 np.int64(1302),
 np.int64(1304),
 np.int64(1306),
 np.int64(1308),
 np.int64(1310),
 np.int64(1312),
 np.int64(1314),
 np.int64(1316),
 np.int64(1318),
 np.int64(1320),
 np.int64(1322),
 np.int64(1324),
 np.int64(1326),
 np.int64(1328),
 np.int64(1330),
 np.int64(1332),
 np.int64(1334),
 np.int64(1336),
 np.int64(1338),
 np.int64(1340),
 np.int64(1342),
 np.int64(1344),
 np.int64(1346),
 np.int64(1348),
 np.int64(1350),
 np.int64(1352),
 np.int64(1354),
 np.int64(1356),
 np.int64(1358),
 np.int64(1360),
 np.int64(1362),
 np.int64(1364),
 np.int64(1366),
 np.int64(1368),
 np.int64(1370),
 np.int64(1372),
 np.int64(1374),
 np.int64(1376),
 np.int64(1378),
 np.int64(1380),
 np.int64(1382),
 np.int64(1384),
 np.int64(1386),
 np.int64(1388),
 np.int64(1390),
 np.int64(1392),
 np.int64(1394),
 np.int64(1396),
 np.int64(1398),
 np.int64(1400),
 np.int64(1402),
 np.int64(1404),
 np.int64(1406),
 np.int64(1408),
 np.int64(1410),
 np.int64(1412),
 np.int64(1414),
 np.int64(1416),
 np.int64(1418),
 np.int64(1420),
 np.int64(1422),
 np.int64(1424),
 np.int64(1426),
 np.int64(1428),
 np.int64(1430),
 np.int64(1432),
 np.int64(1434),
 np.int64(1436),
 np.int64(1438),
 np.int64(1440),
 np.int64(1442),
 np.int64(1444),
 np.int64(1446),
 np.int64(1448),
 np.int64(1450),
 np.int64(1452),
 np.int64(1454),
 np.int64(1456),
 np.int64(1458),
 np.int64(1460),
 np.int64(1462),
 np.int64(1464),
 np.int64(1466),
 np.int64(1468),
 np.int64(1470),
 np.int64(1472),
 np.int64(1474),
 np.int64(1476),
 np.int64(1478),
 np.int64(1480),
 np.int64(1482),
 np.int64(1484),
 np.int64(1486),
 np.int64(1488),
 np.int64(1490),
 np.int64(1492),
 np.int64(1494),
 np.int64(1496),
 np.int64(1498),
 np.int64(1500),
 np.int64(1502),
 np.int64(1504),
 np.int64(1506),
 np.int64(1508),
 np.int64(1510),
 np.int64(1512),
 np.int64(1514),
 np.int64(1516),
 np.int64(1518),
 np.int64(1520),
 np.int64(1522),
 np.int64(1524),
 np.int64(1526),
 np.int64(1528),
 np.int64(1530),
 np.int64(1532),
 np.int64(1534),
 np.int64(1536),
 np.int64(1538),
 np.int64(1540),
 np.int64(1542),
 np.int64(1544),
 np.int64(1546),
 np.int64(1548),
 np.int64(1550),
 np.int64(1552),
 np.int64(1554),
 np.int64(1556),
 np.int64(1558),
 np.int64(1560),
 np.int64(1562),
 np.int64(1564),
 np.int64(1566),
 np.int64(1568),
 np.int64(1570),
 np.int64(1572),
 np.int64(1574),
 np.int64(1576),
 np.int64(1578),
 np.int64(1580),
 np.int64(1582),
 np.int64(1584),
 np.int64(1586),
 np.int64(1588),
 np.int64(1590),
 np.int64(1592),
 np.int64(1594),
 np.int64(1596),
 np.int64(1598),
 np.int64(1600),
 np.int64(1602),
 np.int64(1604),
 np.int64(1606),
 np.int64(1608),
 np.int64(1610),
 np.int64(1612),
 np.int64(1614),
 np.int64(1616),
 np.int64(1618),
 np.int64(1620),
 np.int64(1622),
 np.int64(1624),
 np.int64(1626),
 np.int64(1628),
 np.int64(1630),
 np.int64(1632),
 np.int64(1634),
 np.int64(1636),
 np.int64(1638),
 np.int64(1640),
 np.int64(1642),
 np.int64(1644),
 np.int64(1646),
 np.int64(1648),
 np.int64(1650),
 np.int64(1652),
 np.int64(1654),
 np.int64(1656),
 np.int64(1658),
 np.int64(1660),
 np.int64(1662),
 np.int64(1664),
 np.int64(1666),
 np.int64(1668),
 np.int64(1670),
 np.int64(1672),
 np.int64(1674),
 np.int64(1676),
 np.int64(1678),
 np.int64(1680),
 np.int64(1682),
 np.int64(1684),
 np.int64(1686),
 np.int64(1688),
 np.int64(1690),
 np.int64(1692),
 np.int64(1694),
 np.int64(1696),
 np.int64(1698),
 np.int64(1700),
 np.int64(1702),
 np.int64(1704),
 np.int64(1706),
 np.int64(1708),
 np.int64(1710),
 np.int64(1712),
 np.int64(1714),
 np.int64(1716),
 np.int64(1718),
 np.int64(1720),
 np.int64(1722),
 np.int64(1724),
 np.int64(1726),
 np.int64(1728),
 np.int64(1730),
 np.int64(1732),
 np.int64(1734),
 np.int64(1736),
 np.int64(1738),
 np.int64(1740),
 np.int64(1742),
 np.int64(1744),
 np.int64(1746),
 np.int64(1748),
 np.int64(1750),
 np.int64(1752),
 np.int64(1754),
 np.int64(1756),
 np.int64(1758),
 np.int64(1760),
 np.int64(1762),
 np.int64(1764),
 np.int64(1766),
 np.int64(1768),
 np.int64(1770),
 np.int64(1772),
 np.int64(1774),
 np.int64(1776),
 np.int64(1778),
 np.int64(1780),
 np.int64(1782),
 np.int64(1784),
 np.int64(1786),
 np.int64(1788),
 np.int64(1790),
 np.int64(1792),
 np.int64(1794),
 np.int64(1796),
 np.int64(1798),
 np.int64(1800),
 np.int64(1802),
 np.int64(1804),
 np.int64(1806),
 np.int64(1808),
 np.int64(1810),
 np.int64(1812),
 np.int64(1814),
 np.int64(1816),
 np.int64(1818),
 np.int64(1820),
 np.int64(1822),
 np.int64(1824),
 np.int64(1826),
 np.int64(1828),
 np.int64(1830),
 np.int64(1832),
 np.int64(1834),
 np.int64(1836),
 np.int64(1838),
 np.int64(1840),
 np.int64(1842),
 np.int64(1844),
 np.int64(1846),
 np.int64(1848),
 np.int64(1850),
 np.int64(1852),
 np.int64(1854),
 np.int64(1856),
 np.int64(1858),
 np.int64(1860),
 np.int64(1862),
 np.int64(1864),
 np.int64(1866),
 np.int64(1868),
 np.int64(1870),
 np.int64(1872),
 np.int64(1874),
 np.int64(1876),
 np.int64(1878),
 np.int64(1880),
 np.int64(1882),
 np.int64(1884),
 np.int64(1886),
 np.int64(1888),
 np.int64(1890),
 np.int64(1892),
 np.int64(1894),
 np.int64(1896),
 np.int64(1898),
 np.int64(1900),
 np.int64(1902),
 np.int64(1904),
 np.int64(1906),
 np.int64(1908),
 np.int64(1910),
 np.int64(1912),
 np.int64(1914),
 np.int64(1916),
 np.int64(1918),
 np.int64(1920),
 np.int64(1922),
 np.int64(1924),
 np.int64(1926),
 np.int64(1928),
 np.int64(1930),
 np.int64(1932),
 np.int64(1934),
 np.int64(1936),
 np.int64(1938),
 np.int64(1940),
 np.int64(1942),
 np.int64(1944),
 np.int64(1946),
 np.int64(1948),
 np.int64(1950),
 np.int64(1952),
 np.int64(1954),
 np.int64(1956),
 np.int64(1958),
 np.int64(1960),
 np.int64(1962),
 np.int64(1964),
 np.int64(1966),
 np.int64(1968),
 np.int64(1970),
 np.int64(1972),
 np.int64(1974),
 np.int64(1976),
 np.int64(1978),
 np.int64(1980),
 np.int64(1982),
 np.int64(1984),
 np.int64(1986),
 np.int64(1988),
 np.int64(1990),
 np.int64(1992),
 np.int64(1994),
 np.int64(1996),
 np.int64(1998),
 ...]

In [15]:
%%time
num_list[~(num_list % 2).astype(bool)]

CPU times: user 490 μs, sys: 651 μs, total: 1.14 ms
Wall time: 848 μs

array([   0,    2,    4, ..., 9994, 9996, 9998], shape=(5000,))

In [16]:
num_list[ ~(num_list % 2).astype(bool) ]

array([   0,    2,    4, ..., 9994, 9996, 9998], shape=(5000,))

#### Your turn: Extract all numbers in num_list that end in 7

In [52]:
%%time
ending_in_7 = [n for n in num_list if str(n)[-1] == "7"] #had to make a string to slice
ending_in_7_int = [int(n) for n in ending_in_7]

CPU times: user 5.98 ms, sys: 1.56 ms, total: 7.54 ms
Wall time: 7.49 ms

#### Your turn: Divide each number  in num_list by 2

In [54]:
divide_two = [float(n/2) for n in num_list]
divide_two

[0.0,
 0.5,
 1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5,
 9.0,
 9.5,
 10.0,
 10.5,
 11.0,
 11.5,
 12.0,
 12.5,
 13.0,
 13.5,
 14.0,
 14.5,
 15.0,
 15.5,
 16.0,
 16.5,
 17.0,
 17.5,
 18.0,
 18.5,
 19.0,
 19.5,
 20.0,
 20.5,
 21.0,
 21.5,
 22.0,
 22.5,
 23.0,
 23.5,
 24.0,
 24.5,
 25.0,
 25.5,
 26.0,
 26.5,
 27.0,
 27.5,
 28.0,
 28.5,
 29.0,
 29.5,
 30.0,
 30.5,
 31.0,
 31.5,
 32.0,
 32.5,
 33.0,
 33.5,
 34.0,
 34.5,
 35.0,
 35.5,
 36.0,
 36.5,
 37.0,
 37.5,
 38.0,
 38.5,
 39.0,
 39.5,
 40.0,
 40.5,
 41.0,
 41.5,
 42.0,
 42.5,
 43.0,
 43.5,
 44.0,
 44.5,
 45.0,
 45.5,
 46.0,
 46.5,
 47.0,
 47.5,
 48.0,
 48.5,
 49.0,
 49.5,
 50.0,
 50.5,
 51.0,
 51.5,
 52.0,
 52.5,
 53.0,
 53.5,
 54.0,
 54.5,
 55.0,
 55.5,
 56.0,
 56.5,
 57.0,
 57.5,
 58.0,
 58.5,
 59.0,
 59.5,
 60.0,
 60.5,
 61.0,
 61.5,
 62.0,
 62.5,
 63.0,
 63.5,
 64.0,
 64.5,
 65.0,
 65.5,
 66.0,
 66.5,
 67.0,
 67.5,
 68.0,
 68.5,
 69.0,
 69.5,
 70.0,
 70.5,
 71.0,
 71.5,
 72.0,
 72.5,
 73.0,
 73.5,
 74.0,
 74.5,
 75.0,
 75.5,
 76.0,
 76.5,
 77.0,
 77.5,
 78.0,
 78.5,
 79.0,
 79.5,
 80.0,
 80.5,
 81.0,
 81.5,
 82.0,
 82.5,
 83.0,
 83.5,
 84.0,
 84.5,
 85.0,
 85.5,
 86.0,
 86.5,
 87.0,
 87.5,
 88.0,
 88.5,
 89.0,
 89.5,
 90.0,
 90.5,
 91.0,
 91.5,
 92.0,
 92.5,
 93.0,
 93.5,
 94.0,
 94.5,
 95.0,
 95.5,
 96.0,
 96.5,
 97.0,
 97.5,
 98.0,
 98.5,
 99.0,
 99.5,
 100.0,
 100.5,
 101.0,
 101.5,
 102.0,
 102.5,
 103.0,
 103.5,
 104.0,
 104.5,
 105.0,
 105.5,
 106.0,
 106.5,
 107.0,
 107.5,
 108.0,
 108.5,
 109.0,
 109.5,
 110.0,
 110.5,
 111.0,
 111.5,
 112.0,
 112.5,
 113.0,
 113.5,
 114.0,
 114.5,
 115.0,
 115.5,
 116.0,
 116.5,
 117.0,
 117.5,
 118.0,
 118.5,
 119.0,
 119.5,
 120.0,
 120.5,
 121.0,
 121.5,
 122.0,
 122.5,
 123.0,
 123.5,
 124.0,
 124.5,
 125.0,
 125.5,
 126.0,
 126.5,
 127.0,
 127.5,
 128.0,
 128.5,
 129.0,
 129.5,
 130.0,
 130.5,
 131.0,
 131.5,
 132.0,
 132.5,
 133.0,
 133.5,
 134.0,
 134.5,
 135.0,
 135.5,
 136.0,
 136.5,
 137.0,
 137.5,
 138.0,
 138.5,
 139.0,
 139.5,
 140.0,
 140.5,
 141.0,
 141.5,
 142.0,
 142.5,
 143.0,
 143.5,
 144.0,
 144.5,
 145.0,
 145.5,
 146.0,
 146.5,
 147.0,
 147.5,
 148.0,
 148.5,
 149.0,
 149.5,
 150.0,
 150.5,
 151.0,
 151.5,
 152.0,
 152.5,
 153.0,
 153.5,
 154.0,
 154.5,
 155.0,
 155.5,
 156.0,
 156.5,
 157.0,
 157.5,
 158.0,
 158.5,
 159.0,
 159.5,
 160.0,
 160.5,
 161.0,
 161.5,
 162.0,
 162.5,
 163.0,
 163.5,
 164.0,
 164.5,
 165.0,
 165.5,
 166.0,
 166.5,
 167.0,
 167.5,
 168.0,
 168.5,
 169.0,
 169.5,
 170.0,
 170.5,
 171.0,
 171.5,
 172.0,
 172.5,
 173.0,
 173.5,
 174.0,
 174.5,
 175.0,
 175.5,
 176.0,
 176.5,
 177.0,
 177.5,
 178.0,
 178.5,
 179.0,
 179.5,
 180.0,
 180.5,
 181.0,
 181.5,
 182.0,
 182.5,
 183.0,
 183.5,
 184.0,
 184.5,
 185.0,
 185.5,
 186.0,
 186.5,
 187.0,
 187.5,
 188.0,
 188.5,
 189.0,
 189.5,
 190.0,
 190.5,
 191.0,
 191.5,
 192.0,
 192.5,
 193.0,
 193.5,
 194.0,
 194.5,
 195.0,
 195.5,
 196.0,
 196.5,
 197.0,
 197.5,
 198.0,
 198.5,
 199.0,
 199.5,
 200.0,
 200.5,
 201.0,
 201.5,
 202.0,
 202.5,
 203.0,
 203.5,
 204.0,
 204.5,
 205.0,
 205.5,
 206.0,
 206.5,
 207.0,
 207.5,
 208.0,
 208.5,
 209.0,
 209.5,
 210.0,
 210.5,
 211.0,
 211.5,
 212.0,
 212.5,
 213.0,
 213.5,
 214.0,
 214.5,
 215.0,
 215.5,
 216.0,
 216.5,
 217.0,
 217.5,
 218.0,
 218.5,
 219.0,
 219.5,
 220.0,
 220.5,
 221.0,
 221.5,
 222.0,
 222.5,
 223.0,
 223.5,
 224.0,
 224.5,
 225.0,
 225.5,
 226.0,
 226.5,
 227.0,
 227.5,
 228.0,
 228.5,
 229.0,
 229.5,
 230.0,
 230.5,
 231.0,
 231.5,
 232.0,
 232.5,
 233.0,
 233.5,
 234.0,
 234.5,
 235.0,
 235.5,
 236.0,
 236.5,
 237.0,
 237.5,
 238.0,
 238.5,
 239.0,
 239.5,
 240.0,
 240.5,
 241.0,
 241.5,
 242.0,
 242.5,
 243.0,
 243.5,
 244.0,
 244.5,
 245.0,
 245.5,
 246.0,
 246.5,
 247.0,
 247.5,
 248.0,
 248.5,
 249.0,
 249.5,
 250.0,
 250.5,
 251.0,
 251.5,
 252.0,
 252.5,
 253.0,
 253.5,
 254.0,
 254.5,
 255.0,
 255.5,
 256.0,
 256.5,
 257.0,
 257.5,
 258.0,
 258.5,
 259.0,
 259.5,
 260.0,
 260.5,
 261.0,
 261.5,
 262.0,
 262.5,
 263.0,
 263.5,
 264.0,
 264.5,
 265.0,
 265.5,
 266.0,
 266.5,
 267.0,
 267.5,
 268.0,
 268.5,
 269.0,
 269.5,
 270.0,
 270.5,
 271.0,
 271.5,
 272.0,
 272.5,
 273.0,
 273.5,
 274.0,
 274.5,
 275.0,
 275.5,
 276.0,
 276.5,
 277.0,
 277.5,
 278.0,
 278.5,
 279.0,
 279.5,
 280.0,
 280.5,
 281.0,
 281.5,
 282.0,
 282.5,
 283.0,
 283.5,
 284.0,
 284.5,
 285.0,
 285.5,
 286.0,
 286.5,
 287.0,
 287.5,
 288.0,
 288.5,
 289.0,
 289.5,
 290.0,
 290.5,
 291.0,
 291.5,
 292.0,
 292.5,
 293.0,
 293.5,
 294.0,
 294.5,
 295.0,
 295.5,
 296.0,
 296.5,
 297.0,
 297.5,
 298.0,
 298.5,
 299.0,
 299.5,
 300.0,
 300.5,
 301.0,
 301.5,
 302.0,
 302.5,
 303.0,
 303.5,
 304.0,
 304.5,
 305.0,
 305.5,
 306.0,
 306.5,
 307.0,
 307.5,
 308.0,
 308.5,
 309.0,
 309.5,
 310.0,
 310.5,
 311.0,
 311.5,
 312.0,
 312.5,
 313.0,
 313.5,
 314.0,
 314.5,
 315.0,
 315.5,
 316.0,
 316.5,
 317.0,
 317.5,
 318.0,
 318.5,
 319.0,
 319.5,
 320.0,
 320.5,
 321.0,
 321.5,
 322.0,
 322.5,
 323.0,
 323.5,
 324.0,
 324.5,
 325.0,
 325.5,
 326.0,
 326.5,
 327.0,
 327.5,
 328.0,
 328.5,
 329.0,
 329.5,
 330.0,
 330.5,
 331.0,
 331.5,
 332.0,
 332.5,
 333.0,
 333.5,
 334.0,
 334.5,
 335.0,
 335.5,
 336.0,
 336.5,
 337.0,
 337.5,
 338.0,
 338.5,
 339.0,
 339.5,
 340.0,
 340.5,
 341.0,
 341.5,
 342.0,
 342.5,
 343.0,
 343.5,
 344.0,
 344.5,
 345.0,
 345.5,
 346.0,
 346.5,
 347.0,
 347.5,
 348.0,
 348.5,
 349.0,
 349.5,
 350.0,
 350.5,
 351.0,
 351.5,
 352.0,
 352.5,
 353.0,
 353.5,
 354.0,
 354.5,
 355.0,
 355.5,
 356.0,
 356.5,
 357.0,
 357.5,
 358.0,
 358.5,
 359.0,
 359.5,
 360.0,
 360.5,
 361.0,
 361.5,
 362.0,
 362.5,
 363.0,
 363.5,
 364.0,
 364.5,
 365.0,
 365.5,
 366.0,
 366.5,
 367.0,
 367.5,
 368.0,
 368.5,
 369.0,
 369.5,
 370.0,
 370.5,
 371.0,
 371.5,
 372.0,
 372.5,
 373.0,
 373.5,
 374.0,
 374.5,
 375.0,
 375.5,
 376.0,
 376.5,
 377.0,
 377.5,
 378.0,
 378.5,
 379.0,
 379.5,
 380.0,
 380.5,
 381.0,
 381.5,
 382.0,
 382.5,
 383.0,
 383.5,
 384.0,
 384.5,
 385.0,
 385.5,
 386.0,
 386.5,
 387.0,
 387.5,
 388.0,
 388.5,
 389.0,
 389.5,
 390.0,
 390.5,
 391.0,
 391.5,
 392.0,
 392.5,
 393.0,
 393.5,
 394.0,
 394.5,
 395.0,
 395.5,
 396.0,
 396.5,
 397.0,
 397.5,
 398.0,
 398.5,
 399.0,
 399.5,
 400.0,
 400.5,
 401.0,
 401.5,
 402.0,
 402.5,
 403.0,
 403.5,
 404.0,
 404.5,
 405.0,
 405.5,
 406.0,
 406.5,
 407.0,
 407.5,
 408.0,
 408.5,
 409.0,
 409.5,
 410.0,
 410.5,
 411.0,
 411.5,
 412.0,
 412.5,
 413.0,
 413.5,
 414.0,
 414.5,
 415.0,
 415.5,
 416.0,
 416.5,
 417.0,
 417.5,
 418.0,
 418.5,
 419.0,
 419.5,
 420.0,
 420.5,
 421.0,
 421.5,
 422.0,
 422.5,
 423.0,
 423.5,
 424.0,
 424.5,
 425.0,
 425.5,
 426.0,
 426.5,
 427.0,
 427.5,
 428.0,
 428.5,
 429.0,
 429.5,
 430.0,
 430.5,
 431.0,
 431.5,
 432.0,
 432.5,
 433.0,
 433.5,
 434.0,
 434.5,
 435.0,
 435.5,
 436.0,
 436.5,
 437.0,
 437.5,
 438.0,
 438.5,
 439.0,
 439.5,
 440.0,
 440.5,
 441.0,
 441.5,
 442.0,
 442.5,
 443.0,
 443.5,
 444.0,
 444.5,
 445.0,
 445.5,
 446.0,
 446.5,
 447.0,
 447.5,
 448.0,
 448.5,
 449.0,
 449.5,
 450.0,
 450.5,
 451.0,
 451.5,
 452.0,
 452.5,
 453.0,
 453.5,
 454.0,
 454.5,
 455.0,
 455.5,
 456.0,
 456.5,
 457.0,
 457.5,
 458.0,
 458.5,
 459.0,
 459.5,
 460.0,
 460.5,
 461.0,
 461.5,
 462.0,
 462.5,
 463.0,
 463.5,
 464.0,
 464.5,
 465.0,
 465.5,
 466.0,
 466.5,
 467.0,
 467.5,
 468.0,
 468.5,
 469.0,
 469.5,
 470.0,
 470.5,
 471.0,
 471.5,
 472.0,
 472.5,
 473.0,
 473.5,
 474.0,
 474.5,
 475.0,
 475.5,
 476.0,
 476.5,
 477.0,
 477.5,
 478.0,
 478.5,
 479.0,
 479.5,
 480.0,
 480.5,
 481.0,
 481.5,
 482.0,
 482.5,
 483.0,
 483.5,
 484.0,
 484.5,
 485.0,
 485.5,
 486.0,
 486.5,
 487.0,
 487.5,
 488.0,
 488.5,
 489.0,
 489.5,
 490.0,
 490.5,
 491.0,
 491.5,
 492.0,
 492.5,
 493.0,
 493.5,
 494.0,
 494.5,
 495.0,
 495.5,
 496.0,
 496.5,
 497.0,
 497.5,
 498.0,
 498.5,
 499.0,
 499.5,
 ...]

# 2. Questions: lambda functions

Two questions:

- General syntax (see here for a reference: https://www.w3schools.com/python/python_lambda.asp 
- How they work in the context of aggregations

How is a lambda function different from a "normal" user-defined function (that has the syntax def func_name(arg): etc?

- Operates similarly to normal user-defined functions in that it can take any # of arguments
- Operates differently in that it's an "anonymous" function or a function that we don't explicitly name/save in memory

## 2.1 General syntax for lambda functions

In [48]:
### two pools of courses
socsci = ["QSS20", "QSS17", "GOV10"]
natsci = ["BIO2", "PHYS3"]


## generalize some of the steps
## above into a two-arg function
## that takes the course prefix
## and a list of all courses
def filter_courses(prefix, all_courses):
    rel_courses = [c for c in all_courses if prefix in c]
    return(rel_courses)

### a few applications 
filter_courses(prefix = "QSS", all_courses = socsci)
filter_courses(prefix = "QSS", all_courses = natsci)
filter_courses(prefix = "BIO", all_courses = natsci)

['QSS20', 'QSS17']

[]

['BIO2']

In [49]:
## what's the lambda function version of this
filter_courses_v2 = lambda prefix, all_courses: [c for c in all_courses if prefix in c]
filter_courses_v2(prefix = "BIO", all_courses = natsci)

['BIO2']

## 2.2 using alongside agg

In [ ]:
## use lambda to find modal block in a ward- multiple ways

### way 1: subsetting agg syntex
df.groupby("WARD")["BLOCK"].agg(lambda x: x.mode())

### way 2: dictionary agg syntax
df.groupby("WARD").agg({"BLOCK": lambda x: x.mode()})

#### Your turn: Group by WARD and get the mean and standard deviation (std) of X and Y

In [56]:
df.groupby("WARD")[["X", "Y"]].agg(["mean", "std"])

                  X                           Y
               mean          std           mean          std
WARD
1     397289.867555   624.307287  139648.610621   712.362815
2     396621.067712  1223.488923  137564.793599   595.099248
3     393470.489099  1162.323901  141520.418724  1541.617708
4     397841.637555  1023.793670  143307.153700  1545.603726
5     400915.575468  1297.551690  139152.417438  1416.967174
6     399898.301927   980.505436  136139.856333  1112.374544
7     404563.412110  1626.707129  135648.075402  1388.268228
8     400956.107708  1110.298221  131412.540814  1751.194450

In [57]:
df.groupby("WARD")[['X', 'Y']].agg({lambda x: x.mean(), lambda x: x.std()})

                  X                           Y
         <lambda_0>   <lambda_1>     <lambda_0>   <lambda_1>
WARD
1     397289.867555   624.307287  139648.610621   712.362815
2     396621.067712  1223.488923  137564.793599   595.099248
3     393470.489099  1162.323901  141520.418724  1541.617708
4     397841.637555  1023.793670  143307.153700  1545.603726
5     400915.575468  1297.551690  139152.417438  1416.967174
6     399898.301927   980.505436  136139.856333  1112.374544
7     404563.412110  1626.707129  135648.075402  1388.268228
8     400956.107708  1110.298221  131412.540814  1751.194450

### Random sampling and distance measures

In [ ]:
random_uniform = np.random.rand(5)  # 5 random numbers between 0 and 1
print("Random numbers from uniform distribution:", random_uniform)

random_normal = np.random.randn(5)  # 5 random numbers from a standard normal distribution
print("Random numbers from normal distribution:", random_normal)

In [ ]:
N = 200

sns.kdeplot(np.random.rand(N))

In [ ]:
sns.kdeplot(np.random.randn(N))